<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Render\Markup;

/**
 * Implements hook_form_alter().
 */
function hcpss_classified_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-listing-page-1') {
    /** @var \Drupal\taxonomy\TermStorage $storage */
    $storage = \Drupal::entityTypeManager()
      ->getStorage('taxonomy_term');

    $categories = $storage->loadTree('category');

    $options_formatter = function (array $terms) {
      return array_reduce($terms, function ($carry, $item) {
        $label = $item->parents[0] ? "- {$item->name}" : $item->name;
        $carry[$item->name] = $label;
        return $carry;
      }, ['' => '- Any -']);
    };

    $form['categories_name'] = [
      '#type' => 'select',
      '#title' => t('Category'),
      '#options' => $options_formatter($categories),
    ];
  }
}

/**
 * Implements hook_mail().
 */
function hcpss_classified_mail($key, &$message, $params) {
  switch ($key) {
    case 'hcpss_classified_checkout':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = 'An inventory request has been made';
      $message['headers']['Content-Type'] = 'text/html';

      $template_path = \Drupal::service('extension.list.module')
          ->getPath('hcpss_classified') . '/templates/email/checkout.html.twig';

      $template = \Drupal::service('twig')->loadTemplate($template_path);

      $node = Node::load($params['nid']);
      $message['body'][] = Markup::create($template->render([
        'node' => $node,
        'line_items' => $node->field_line_items->referencedEntities(),
      ]));
      break;
  }
}
