---
services:
  drupal:
    networks:
      - testing
  chrome:
    container_name: swap_chrome
    image: seleniarm/standalone-chromium
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    networks:
      - testing
  selenium:
    container_name: swap_selenium
    image: banderson/selenium
    volumes:
      - ./selenium:/app
    command: tail -f /dev/null
    networks:
      - testing
