---
services:
  mailhog:
    container_name: swap_mailhog
    image: banderson/mailhog
    user: root
    expose:
      - "25"
    ports:
      - 8030:8025
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:25
    networks:
      testing:
      email:
        aliases:
          - email-smtp.us-east-1.amazonaws.com
  db:
    container_name: swap_db
    image: mariadb:10.8
    volumes:
      - ./.data:/var/lib/mysql
      - ./drupal.sql:/docker-entrypoint-initdb.d/drupal.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M
    networks:
      - database
  drupal:
    container_name: swap_web
    depends_on:
      - db
    image: reg.hcpss.org/schoolswap/web:${VERSION:-dev}
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8200:80"
    volumes:
      - ./drupal:/var/www/drupal
      #- ./.files/public_files:/var/www/drupal/web/sites/default/files
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      COMPOSER_PROCESS_TIMEOUT: 2000
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DRUPAL_ENV: dev
      SAML_BASE_URL: ${SAML_BASE_URL}
      SAML_SALT: ${SAML_SALT}
      SAML_ADMIN_PASSWORD: ${SAML_ADMIN_PASSWORD}
    command: >
      bash -c "drush --root=/var/www/drupal/web upwd admin admin
      && apache2-foreground"
#    entrypoint: tail -f /dev/null
    networks:
      database:
      email:
      testing:

networks:
  database:
  email:
  testing:
