---
version: '3.5'

services:
  mailhog:
    container_name: classified_mailhog
    image: mailhog/mailhog
    user: root
    expose:
      - "25"
    ports:
      - 8030:8025
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:25
    networks:
      testing:
      email:
        aliases:
          - ironport.hcpss.org

  db:
    container_name: classified_db
    image: mysql:5.7
    volumes:
      - ./.data:/var/lib/mysql
      # - ./drupal.sql:/docker-entrypoint-initdb.d/drupal.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M
    networks:
      - database

  drupal:
    container_name: classified_web
    depends_on:
      - db
    image: "reg.hcpss.org/schoolswap/web:dev"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      #- "8124:80"
      - "8083:80"
    volumes:
      - ./drupal:/var/www/drupal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      COMPOSER_PROCESS_TIMEOUT: 2000
      DRUPAL_ENV: dev
    # extra_hosts:
    #  - "mpia.hcpss.localhost:127.0.0.1"
#    command: >812
#      bash -c "drush --root=/var/www/drupal/web upwd banderson admin
#      && apache2-foreground"
#    entrypoint: tail -f /dev/null
    networks:
      database:
      email:
      testing:
        # aliases:
        #   - mpia.hcpss.localosts

networks:
  database:
  email:
  testing:
